---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Copy logstash configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-inputs.conf
    - 05-firewall.conf
    - 10-others.conf
    - 20-suricata.conf
    - 25-snort.conf
    - 30-geoip.conf
    - 40-dns.conf
    - 45-cleanup.conf
    - 50-outputs.conf

- name: Create patterns directory
  file:
    path: /etc/logstash/conf.d/patterns
    state: directory
    mode: '0744'

- name: Copy pattern file
  copy:
    src: files/patterns/pfelk.grok
    dest: /etc/logstash/conf.d/patterns/pfelk.grok
    owner: root
    group: root
    mode: '0644'

- name: Create template directory
  file:
    path: /etc/logstash/conf.d/templates
    state: directory
    mode: '0744'

- name: Copy template file
  copy:
    src: files/template/pf-geoip-template.json
    dest: /etc/logstash/conf.d/templates/pf-geoip-template.json
    owner: root
    group: root
    mode: '0644'

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
