---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/etc/logstash/conf.d/patterns'
    - '/etc/logstash/conf.d/templates'
    - '/etc/logstash/conf.d/databases'
    
- name: Directories Permissions
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - '/etc/logstash/conf.d/patterns'
    - '/etc/logstash/conf.d/templates'
    - '/etc/logstash/conf.d/databases'

- name: Copy pfELK Files
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: '01-inputs.conf', dest: '/etc/logstash/conf.d' }
    - { src: '02-types.conf', dest: '/etc/logstash/conf.d' }
    - { src: '03-filter.conf', dest: '/etc/logstash/conf.d' }
    - { src: '05-firewall.conf', dest: '/etc/logstash/conf.d' }
    - { src: '10-apps.conf', dest: '/etc/logstash/conf.d' }
    - { src: '30-geoip.conf', dest: '/etc/logstash/conf.d' }
    - { src: '35-rules-desc.conf', dest: '/etc/logstash/conf.d' }
    - { src: '36-ports-desc.conf', dest: '/etc/logstash/conf.d' }
    - { src: '45-cleanup.conf', dest: '/etc/logstash/conf.d' }
    - { src: '50-outputs.conf', dest: '/etc/logstash/conf.d' }
    - { src: 'pfelk.grok', dest: '/etc/logstash/conf.d/patterns' }
    - { src: 'pfelk.json', dest: '/etc/logstash/conf.d/templates' }
    - { src: 'haproxy.json', dest: '/etc/logstash/conf.d/templates' }
    - { src: 'pfelk-geoip.json', dest: '/etc/logstash/conf.d/templates' }

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
