---

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present

- name: Add elasticsearch repository
  apt_repository: repo={{ es_apt_url }} state=present

- name: Install logstash
  apt: name=logstash state=present

- name: Create Required Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
    owner: root
    group: root
    mode: '0744'
  with_items:
    - '/etc/logstash/conf.d/patterns'
    - '/etc/logstash/conf.d/templates'
    - '/etc/logstash/conf.d/databases'

- name: Copy pfELK Files
  copy: 
    src: "{{ item }}" 
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 01-inputs.conf
    - 02-types.conf
    - 03-filter.conf
    - 05-firewall.conf
    - 10-apps.conf
    - 30-geoip.conf
    - 35-rules-desc.conf
    - 36-ports-desc.conf
    - 45-cleanup.conf
    - 50-outputs.conf

- name: Copy patterns file
  copy:
    src: files/patterns/pfelk.grok
    dest: /etc/logstash/conf.d/patterns/pfelk.grok
    owner: root
    group: root
    mode: '0644'

- name: Copy templates file
  copy:
    src: files/templates/pfelk-geoip.json
    dest: /etc/logstash/conf.d/templates/pfelk-geoip.json
    owner: root
    group: root
    mode: '0644'

- name: Copy database files
  copy:
    src: files/databases/rule-names.csv
    src: files/databases/service-names-port-numbers.csv
    dest: /etc/logstash/conf.d/databases/
    owner: root
    group: root
    mode: '0644'  

- name: Start logstash
  systemd:
    name: logstash
    daemon_reload: yes
    state: started
    enabled: yes
