---
sudo: required

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
#  - ANSIBLE_VERSION=2.9.4
#  - ANSIBLE_VERSION=2.9.3
#  - ANSIBLE_VERSION=2.9.2
#  - ANSIBLE_VERSION=2.9.1


branches:
  only:
    - master

before_install:
  - sudo apt update -qq

install:
  - sudo apt-get install sshpass
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i hosts deploy-stack.yml --syntax-check
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook --connection=local -vvvv --check deploy-stack.yml


