--- 

- name: Install Elasticsearch repository
  become: yes
  block:
  - name: Debian - Install apt-transport-https to support https APT downloads
    apt:
      name: apt-transport-https
      state: present

  - name: Debian - Add Elasticsearch repository key
    apt_key:
      url: '{{ es_apt_key }}'
      state: present

  - name: Debian - Add elasticsearch repository
    apt_repository:
      repo: '{{ item.repo }}'
      state: '{{ item.state }}'
    with_items:
      - { repo: "{{ es_apt_url }}", state: "present" }

- name: Install kibana
  apt:
    name: kibana

- name: Copy kibana configuration
  copy:
    src: "../files/kibana.yml"
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644

- name: Start kibana
  systemd:
    name: kibana
    daemon_reload: yes
    state: started
    enabled: yes
