---

- name: Install openjdk repository
  become: yes
  block:
  - name: Add repository
    apt-repository:
      repo: ppa:openjdk-r/ppa
      update_cache: yes
      state: present

- name: Install OpenJDK Java
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jdk
