---

- name: Install openjdk repository
  become: yes
  block:
  - name: Add repository
    apt:
      name: ppa:openjdk-r/ppa
      state: present

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Install OpenJDK Java
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jdk
