--- 

- name: Install Elasticsearch repository
  become: yes
  block:
  - name: Debian - Install apt-transport-https to support https APT downloads
    apt:
      name: apt-transport-https
      state: present

  - name: Debian - Add Elasticsearch repository key
    apt_key:
      key: '{{ es_apt_key }}'
      state: present

  - name: Debian - Add elasticsearch repository
    apt_repository:
      repo: '{{ item.repo }}'
      state: '{{ item.state }}'
    with_items:
      - { repo: "{{ es_apt_url_old }}", state: "absent" }
      - { repo: "{{ es_apt_url }}", state: "present" }
      - { repo: "{{ es_other_apt_url }}", state: "absent" }

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Copy elasticsearch configuration
  copy:
    src: "../files/elasticsearch.yml"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: elasticsearch
    mode: 0644
  notify: restart elasticsearch

- name: Install python pip
  apt:
    name: python-pip
    state: present

- name: Install python setuptools
  apt:
    name: python-setuptools
    state: present

- name: Start elasticsearch
  systemd:
    name: elasticsearch
    daemon_reload: yes
    state: started
    enabled: yes
